use_frameworks!

def libraries

    pod 'SnapKit'
    pod 'FDFullscreenPopGesture'
    
    # 图片裁剪框架
    pod 'CropViewController'

    # 奔溃收集
    pod 'Bugly'
end

target 'InTime' do
    platform :ios, '9.0'
    libraries
end
