use_frameworks!

def libraries

    pod 'SnapKit'
    pod 'FDFullscreenPopGesture'
    
    # 图片裁剪框架
    pod 'CropViewController'
    
    # 倒计时动画框架
    pod 'CountdownLabel'

end

target 'InTime' do
    platform :ios, '9.0'
    libraries
end
